package com.github.jlance.compat;

import static org.junit.jupiter.api.Assertions.*;

import com.github.jlance.format.LanceFileReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.apache.arrow.memory.BufferAllocator;
import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.IntVector;
import org.apache.arrow.vector.UInt1Vector;
import org.apache.arrow.vector.VectorSchemaRoot;
import org.junit.jupiter.api.Test;

/**
 * Compatibility tests for Milestone 39: V2.1 InlineBitpacking / compressive encodings.
 *
 * <p>Reads a Python-generated Lance V2.1 file and verifies the Java decoder produces
 * identical values for InlineBitpacking and nullable InlineBitpacking columns.
 */
public class Milestone39CompatTest {

  private static final Path DATA_DIR = Paths.get("..", "compat_tests", "data", "milestone_39");

  // Expected values generated by compat_tests/milestone_39_gen.py with seed=42
  private static final int[] SMALL_INT_FIRST_20 = {
    1, 12, 10, 7, 6, 13, 1, 11, 3, 1, 8, 15, 11, 12, 11, 12, 8, 2, 13, 7
  };
  private static final int[] SMALL_INT_LAST_10 = {
    4, 14, 11, 11, 4, 15, 7, 8, 12, 10
  };

  private static final Integer[] SMALL_NULLABLE_FIRST_20 = {
    null, 2, 2, 7, 5, 2, 5, 5, 3, 3, null, 4, 1, 5, 4, 4, 5, 7, 2, 3
  };
  private static final Integer[] SMALL_NULLABLE_LAST_10 = {
    null, 0, 2, 3, 7, 4, 4, 1, 6, 2
  };

  private static final int[] U8_COL_FIRST_20 = {
    85, 236, 132, 23, 144, 118, 214, 252, 23, 125,
    168, 48, 223, 173, 39, 4, 164, 39, 237, 19
  };
  private static final int[] U8_COL_LAST_10 = {
    187, 33, 167, 23, 237, 216, 27, 83, 179, 144
  };

  @Test
  public void testBitpacking() throws Exception {
    Path file = DATA_DIR.resolve("test_bitpacking.lance");
    try (BufferAllocator allocator = new RootAllocator();
        LanceFileReader reader = new LanceFileReader(file)) {
      try (VectorSchemaRoot root = reader.readBatch(allocator)) {
        assertEquals(2050, root.getRowCount());

        // Column 0: small_int (InlineBitpacking, all valid)
        IntVector smallIntVec = (IntVector) root.getVector("small_int");
        assertEquals(2050, smallIntVec.getValueCount());
        for (int i = 0; i < SMALL_INT_FIRST_20.length; i++) {
          assertEquals(SMALL_INT_FIRST_20[i], smallIntVec.get(i),
              "small_int mismatch at index " + i);
        }
        int rowCount = root.getRowCount();
        for (int i = 0; i < SMALL_INT_LAST_10.length; i++) {
          int idx = rowCount - SMALL_INT_LAST_10.length + i;
          assertEquals(SMALL_INT_LAST_10[i], smallIntVec.get(idx),
              "small_int mismatch at index " + idx);
        }

        // Column 1: small_nullable (nullable InlineBitpacking)
        IntVector smallNullableVec = (IntVector) root.getVector("small_nullable");
        assertEquals(2050, smallNullableVec.getValueCount());
        for (int i = 0; i < SMALL_NULLABLE_FIRST_20.length; i++) {
          Integer expected = SMALL_NULLABLE_FIRST_20[i];
          if (expected == null) {
            assertTrue(smallNullableVec.isNull(i),
                "small_nullable should be null at index " + i);
          } else {
            assertFalse(smallNullableVec.isNull(i),
                "small_nullable should not be null at index " + i);
            assertEquals(expected.intValue(), smallNullableVec.get(i),
                "small_nullable mismatch at index " + i);
          }
        }
        for (int i = 0; i < SMALL_NULLABLE_LAST_10.length; i++) {
          int idx = rowCount - SMALL_NULLABLE_LAST_10.length + i;
          Integer expected = SMALL_NULLABLE_LAST_10[i];
          if (expected == null) {
            assertTrue(smallNullableVec.isNull(idx),
                "small_nullable should be null at index " + idx);
          } else {
            assertFalse(smallNullableVec.isNull(idx),
                "small_nullable should not be null at index " + idx);
            assertEquals(expected.intValue(), smallNullableVec.get(idx),
                "small_nullable mismatch at index " + idx);
          }
        }

        // Column 2: u8_col (Flat 8-bit)
        UInt1Vector u8Vec = (UInt1Vector) root.getVector("u8_col");
        assertEquals(2050, u8Vec.getValueCount());
        for (int i = 0; i < U8_COL_FIRST_20.length; i++) {
          assertEquals(U8_COL_FIRST_20[i], u8Vec.get(i) & 0xFF,
              "u8_col mismatch at index " + i);
        }
        for (int i = 0; i < U8_COL_LAST_10.length; i++) {
          int idx = rowCount - U8_COL_LAST_10.length + i;
          assertEquals(U8_COL_LAST_10[i], u8Vec.get(idx) & 0xFF,
              "u8_col mismatch at index " + idx);
        }
      }
    }
  }
}
